# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f43eb60aebb8b9845be4611147ff0ad84984156a3f74af58e687b1c68251e030205fdba8d45f4fd1a1736f8ca5231181a1245e8a36dca4bf4990087a325f14a

test:
  secret_key_base: 1fc52156f1088d52b26b92084f5c8a7104ff1acd5fb27fde11f50753a7a46a75b7aea347575d62865ebd7b56efde4bc66ae98050800a03bd275843bcc0a40bc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
